version: "3.7"

services:
  chaddi-tg:
    container_name: chaddi-tg
    image: arkits/chaddi-tg
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    ports:
      - "5100:5100"

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    command: --config.file=/etc/prometheus/prometheus.yml
    expose:
      - 9090
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./docker-data/prometheus-data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      # - ./grafana.ini:/etc/grafana/grafana.ini
      - ./docker-data/grafana-data:/var/lib/grafana
    environment:
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./docker-data/postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
