from handlers import default
from handlers import error
from handlers import hi
from handlers import about
from handlers import calc
from handlers import choose
from handlers import good_morning
from handlers import mom
from handlers import gamble
from handlers import quotes